version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 20

  consumer:
    build: .dev
    image: thumper-php:latest

    volumes:
      - .:/plugin
      - go-pkg:/root/go/pkg
      - go-cache:/root/.cache
      - docker-cache:/.composer
    environment:
      COMPOSER_CACHE_DIR: /.composer/cache
    depends_on:
      rabbitmq:
        condition: service_healthy
    working_dir: /plugin/.dev/worker

    command: ./worker.sh

  velox:
    image: ghcr.io/roadrunner-server/velox:2024.1.3
    volumes:
      - .:/plugin
      - go-pkg:/root/go/pkg
      - go-cache:/root/.cache
    working_dir: /plugin
    environment:
      VERSION: ''
      TIME: ''

      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    command: build -c velox_rr.toml -o /plugin
    env_file:
      - .env

volumes:
  go-cache:
  go-pkg:
  docker-cache:
